### ISSUE TITLE
Use .default instead of _calc

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#143]
This way we could use matrices as inputs. What do you think @mhesselbarth ?

Example: https://github.com/r-spatialecology/landscapemetrics/commit/8630067278f6f8d4a43ba6483ad15ad218fc733e

**Comment by mhesselbarth** [comment]
I think we discussed and agreed on to not allow matrices as input. The main problem with matrices is that there is no information about the resolution of the cells which makes all metrics that use the area or the perimeter impossible to calculate without additionally it. In the publication, we even argue that this is one of the advantages over SDMTools (less error-prone because all information is gather from raster directly).
