### ISSUE TITLE
Store results for calculate_lsm

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#154]
Not sure how complicated this will be (if even possible), but maybe we can somehow store results for e.g. the patch area and other values we need for several metrics during the calculation of `calculate_lsm()` so we don't need to calculate them n times.

**Comment by bitbacchus** [comment]
Would make sense...

We'd need some class where we can store values and intermediate values as member variables alongside the functions. Each time such a value is needed in a function, it is retrieved from the member variable if it was calculated, already. Otherwise, it is calculated and stored to that member variable.

An alternative could be to give each function a List as an additional parameter, where it retrieves values if existing or stores them if not existing. This List is passed from one metric calculation to the next.

Maybe we should try one of the two with say, patch area, and see how messy it gets.

**Comment by mhesselbarth** [comment]
Yes, that was my idea as well. I will have a look in the new year :)

**Comment by bitbacchus** [comment]
Idea: we could change `landscapemetrics` so that there would always be an `lsm` _object_ on which the calculations would be performed, e.g.

```
lsm <- lsm(landscape_raster)

circle <- lsm.p_circle(directions = 8)
metrics <- lsm.calculate(level = c("class", "landscape"), 
                                 type = "aggregation metric")
```
This way, all interim results for the individual metrics could be saved in the `lsm` object and reused for subsequent calculations. And the `lsm` object can also be used as a container format, in which the raster can be stored/saved together with the calculated metrics.

**Comment by mhesselbarth** [comment]
Not sure if I like this idea. I see that this approach would make it quite easy to store all the information needed. However, I like that is is currently possible to use raster objects without any need to modify/change/convert them. I think that this makes it convenient for many applications (e.g. allows to use a pipe quite easily).

**Comment by bitbacchus** [comment]
Just a note, [PyLandStats](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0225734) apparently has this feature. Maybe we can get some inspirations from there.

**Comment by mhesselbarth** [comment]
FYI @Nowosad made some major progress and will be part of `v2.1`

**Comment by Nowosad** [comment]
WIP at https://github.com/r-spatialecology/landscapemetrics/tree/commoncalcs

**Comment by Nowosad** [comment]
https://github.com/r-spatialecology/landscapemetrics/pull/308
