### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by laurajanegraham** [r-spatialecology/landscapemetrics#30]
I've had a look over the vignettes. It's looking fantastic and really well explained. I've made a few small corrections (typos and additional clarification where needed). Do you want me to just push, or would you prefer me to fork and do a pull request? 

Some points on which I did not want to make large changes: 

# General points
- Do you have any plans to allow for vector input? I can see cases in which this would be useful. Or do you think they may be so limited that it's fine to expect users to rasterize their data. 
- Core metrics: currently depth of edge is fixed to 1 cell. Might this be problematic for some uses because it is directly dependent on the resolution of the data. Could this be something a user specifies? 

# Utility functions
- Connected labelling plots: viridis colour scheme doesn't really work very well in this case (especially plot 3 - the difference between colours is not visible) - is there another colour scheme that could be used?
- Get adjacencies - need explanation of the second parameter (given as 4), why is 1-NA in the explanation? Also explanation of the output. I've also added a separate issue about this function. 

# Functions
- I think it would be useful to have the names in full on this page (rather than the fragstats abbreviations). Some users won't be familiar with FRAGSTATS and it's a pain to click through to the page just to see what the function does if it's not immediately obvious. 

I'll have a look at the functions in more depth and send any thoughts about those.

**Comment by marcosci** [comment]
Thanks so much Laura :blush: 

1. You have full admin rights here, so go nuts :smile: Only thing to consider now is: if you change something, please make a branch with the changes and then if everything works we merge it back. Reason is, that the master branch will now only contain the CRAN version and develop should be a stable version with new stuff in between CRAN submissions. So if we develop something new, that should happen in a branch.

> Do you have any plans to allow for vector input? I can see cases in which this would be useful. Or do you think they may be so limited that it's fine to expect users to rasterize their data.

We had that at some point and I actually forgot what the outcome was ... As all of the metrics so far only make sense with gridded data ... maybe we could show fasterize and how you use it in any of the vignettes? But we maybe should start brainstorming about landscape metrics for vector data :-P

> Core metrics: currently depth of edge is fixed to 1 cell. Might this be problematic for some uses because it is directly dependent on the resolution of the data. Could this be something a user specifies?

Sure, just need to run boundaries then as often as one species the edge depth. Good idea :-)

> Connected labelling plots: viridis colour scheme doesn't really work very well in this case (especially plot 3 - the difference between colours is not visible) - is there another colour scheme that could be used?

Makes sense, will be changed.

> I think it would be useful to have the names in full on this page (rather than the fragstats abbreviations). Some users won't be familiar with FRAGSTATS and it's a pain to click through to the page just to see what the function does if it's not immediately obvious.

There is a tibble that Max wrote with all the full names and categories for the metrics.It is also described at the end of the getstarted vignette:

https://landscapeecology.github.io/landscapemetrics/articles/getstarted.html

Is that what you meant?

**Comment by mhesselbarth** [comment]
I think the way to go on from here, is to create a new branch from the develop branch whenever someone wants to add or modify the code. Once everything is running smoothly we can merge the new branch into the development branch. The development branch would be the stable one for installing the package from GitHub, while the master branch would be the one for the CRAN releases. So feel free the create a new branch whenever you want :)

## General points
- We thought about vector input but decided this may be a feature for the future. We decided to concentrate on rasters first. Maybe we can add the vector support some time in the future. The quick and dirty way would be to simply rasterise the vectors. However, @marcosci had the idea to even develop landscape metrics for vectors. But this would probably be a package on its own.
- Adding a way to specify the core depth would definitely be a cool option and something we need to tackle in the future. Currently, we did not have an idea how to code this while not slowing down the code too much for large rasters.

## Utility functions
- I'm not very much into colour schemes, but if there is one more suitable I would be happy to change the function :) Maybe we could even code in a way the user can specify the colour scheme...
- Valid point :) Will look at this on monday

## Functions
- The problem is that the page is created automatically from the actual R-function names. Not sure if it is possible to change that.
